apiVersion: v1
kind: Pod
metadata:
  generateName: sglang-demo-
  namespace: default
spec:
  runtimeClassName: cedana # required for GPU C/R support (use nvidia for native)
  containers:
    - name: sg-lang-demo
      image: lmsysorg/sglang:latest
      args:
        - python3
        - -m
        - sglang.launch_server
        - --model-path
        - openai-community/gpt2
        - --host
        - 0.0.0.0
        - --port
        - "30000"
      resources:
        limits:
          nvidia.com/gpu: 1
