apiVersion: v1
kind: Pod
metadata:
  generateName: openmm-simulatepdb-
  namespace: default
spec:
  runtimeClassName: cedana
  containers:
    - name: openmm-simulatepdb
      image: cedana/cedana-samples:compbio
      command:
        - bash
        - -c
        - cd gpu_smr/compbio/openmm/examples/python-examples && python3 simulatePdb.py
      env:
        - name: OPENMM_DEFAULT_PLATFORM
          value: CUDA
      resources:
        limits:
          nvidia.com/gpu: 1

